# Generated by Django 5.1.2 on 2024-11-10 11:17

import booking_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['cargo', 'seat']},
        ),
        migrations.AddField(
            model_name='station',
            name='image',
            field=models.ImageField(null=True, upload_to=booking_service.models.station_image_file_path),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('trip', 'cargo', 'seat')},
        ),
    ]
